spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# spring.datasource.initialization-mode=embedded
spring.sql.init.mode=embedded

# Actuator + Prometheus metrics
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
management.metrics.tags.application=database_service_project
management.metrics.distribution.percentiles-histogram.http.server.requests=true
